# This is a basic workflow to help you get started with Actions

name: Development + Testing

on: 
  push: 
    branches:
      - update/*
      - development
      - main

jobs: 
  Lint: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Terraform-Lint
        uses: actionshub/terraform-lint@1.0.0
  Build:
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo The infrastructure has been built!
  
  Test:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo ${{ github.event.ref }}
  
  DeployDev:
    name: Deploy to Dev 
    if: github.event.ref == 'refs/heads/development'
    needs: [Test]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: echo ${{ github.event.pull_request.base.ref }}
  
  DeployStaging: 
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Test]
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Stage
        run: echo I am staging!
  
  
  DeployProduction:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - name: Produce
        run: echp Going into production!
  
  


