# This is a basic workflow to help you get started with Actions

name: CI + CD

on: 
  push: 
    branches:
      - update/*
      - development
      - main
  pull_request:
    branches: 
      - main

jobs: 
  Lint: 
    if: github.event_name == 'push'
    runs-on: ubuntu-latest 
    steps: 
      - name: Terraform-Lint
        uses: actionshub/terraform-lint@1.0.0
        
  Build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [Lint]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo The infrastructure has been built!
        
  Test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo ${{ github.head.ref }}
        
  CheckPull:
    name: Validate Pull to Main
    if: (github.event_name == 'pull_request') && (github.pull_request.head.ref != 'development')
    runs-on: ubuntu-latest
    steps: 
    - name: Debug
      run: echo $GITHUB_BASE_REF
    - name: Failure
      run: exit 1
  
  DeployDev:
    name: Deploy to Dev 
    if: github.event.ref == 'refs/heads/development'
    needs: [Test]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: echo ${{ github.event.pull_request.base.ref }}
  
  DeployStaging: 
    name: Deploy to Staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Test]
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Stage
        run: echo I am staging!
  
  DeployProduction:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      - name: Produce
        run: echo Going into production!
  
  


